### ISSUE TITLE
Where are the build instructions?

### ISSUE THREAD

**Issue by funarog** [velveteer/hermes#15]
Where are the instructions on how to build hermes?  Tried the following on MacOS Monterey 12.6
👍 
% cabal --version
cabal-install version 3.8.1.0

% cabal update
Downloading the latest package list from hackage.haskell.org
Package list of hackage.haskell.org has been updated.
The index-state is set to 2022-10-10T16:14:10Z.
To revert to previous state run:
    cabal v2-update 'hackage.haskell.org,2022-01-03T18:47:46Z'
gregory@our-imac hermes % cabal build
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: hermes-json-0.2.0.0 (user goal)
[__1] next goal: base (dependency of hermes-json)
[__1] rejecting: base-4.17.0.0/installed-4.17.0.0 (conflict: hermes-json =>
base>=4.13 && <4.17)
[__1] skipping: base-4.17.0.0 (has the same characteristics that caused the
previous version to fail: excluded by constraint '>=4.13 && <4.17' from
'hermes-json')
[__1] rejecting: base-4.16.3.0, base-4.16.2.0, base-4.16.1.0, base-4.16.0.0,
base-4.15.1.0, base-4.15.0.0, base-4.14.3.0, base-4.14.2.0, base-4.14.1.0,
base-4.14.0.0, base-4.13.0.0, base-4.12.0.0, base-4.11.1.0, base-4.11.0.0,
base-4.10.1.0, base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0,
base-4.8.1.0, base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0,
base-4.6.0.1, base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0,
base-4.4.0.0, base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1,
base-4.2.0.0, base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1
(constraint from non-upgradeable package requires installed instance)
[__1] fail (backjumping, conflict set: base, hermes-json)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, hermes-json

**Comment by velveteer** [comment]
What version of GHC are you using?

**Comment by funarog** [comment]
Thanks for the quick response !


% ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.4.1

**Comment by velveteer** [comment]
I haven't yet updated and released hermes-json to support 9.4.1 (base-4.17.0.0). If you can use GHC 9.2.4 that should still work on Monterey 12.6. In the meantime I will look into getting 9.4.1 support into the next release.

**Comment by funarog** [comment]
Thanks.  I changed the hermes-json.cabal at line 62. It appears to build.

from 	base               >= 4.13 && < 4.17
to:	base               >= 4.13,

output:

***@***.*** hermes % cabal build
Resolving dependencies...
Build profile: -w ghc-9.4.1 -O1
In order, the following will be built (use -v for more details):
 - base-compat-0.12.2 (lib) (requires download & build)
 - base-orphans-0.8.7 (lib) (requires download & build)
 - dlist-1.0 (lib) (requires build)
 - hashable-1.4.1.0 (lib) (requires download & build)
 - unliftio-core-0.2.0.1 (lib) (requires download & build)
 - integer-logarithms-1.0.3.1 (lib) (requires build)
 - primitive-0.7.4.0 (lib) (requires download & build)
 - attoparsec-0.14.4 (lib:attoparsec-internal) (requires download & build)
 - base-compat-batteries-0.12.2 (lib) (requires download & build)
 - time-compat-1.9.6.1 (lib) (requires build)
 - async-2.2.4 (lib) (requires download & build)
 - scientific-0.3.7.0 (lib) (requires build)
 - unliftio-0.2.22.0 (lib) (requires download & build)
 - attoparsec-0.14.4 (lib) (requires download & build)
 - attoparsec-iso8601-1.0.2.1 (lib) (requires download & build)
 - hermes-json-0.2.0.0 (lib) (first run)
Downloading  base-orphans-0.8.7
Starting     dlist-1.0 (lib)
Downloaded   base-orphans-0.8.7
Downloading  unliftio-core-0.2.0.1
Starting     base-orphans-0.8.7 (lib)
Downloaded   unliftio-core-0.2.0.1
Downloading  primitive-0.7.4.0
Downloaded   primitive-0.7.4.0
Downloading  base-compat-0.12.2
Downloaded   base-compat-0.12.2
Downloading  base-compat-batteries-0.12.2
Starting     base-compat-0.12.2 (lib)
Downloaded   base-compat-batteries-0.12.2
Downloading  hashable-1.4.1.0
Downloaded   hashable-1.4.1.0
Downloading  async-2.2.4
Starting     hashable-1.4.1.0 (lib)
Downloaded   async-2.2.4
Downloading  unliftio-0.2.22.0
Downloaded   unliftio-0.2.22.0
Downloading  attoparsec-0.14.4
Downloaded   attoparsec-0.14.4
Downloading  attoparsec-iso8601-1.0.2.1
Downloaded   attoparsec-iso8601-1.0.2.1
Building     hashable-1.4.1.0 (lib)
Building     base-orphans-0.8.7 (lib)
Building     base-compat-0.12.2 (lib)
Building     dlist-1.0 (lib)
Installing   hashable-1.4.1.0 (lib)
Installing   dlist-1.0 (lib)
Installing   base-orphans-0.8.7 (lib)
Completed    hashable-1.4.1.0 (lib)
Starting     unliftio-core-0.2.0.1 (lib)
Completed    dlist-1.0 (lib)
Starting     integer-logarithms-1.0.3.1 (lib)
Completed    base-orphans-0.8.7 (lib)
Starting     primitive-0.7.4.0 (lib)
Building     integer-logarithms-1.0.3.1 (lib)
Building     unliftio-core-0.2.0.1 (lib)
Building     primitive-0.7.4.0 (lib)
Installing   unliftio-core-0.2.0.1 (lib)
Completed    unliftio-core-0.2.0.1 (lib)
Starting     attoparsec-0.14.4 (lib:attoparsec-internal)
Building     attoparsec-0.14.4 (lib:attoparsec-internal)
Installing   integer-logarithms-1.0.3.1 (lib)
Completed    integer-logarithms-1.0.3.1 (lib)
Starting     async-2.2.4 (lib)
Building     async-2.2.4 (lib)
Installing   attoparsec-0.14.4 (lib:attoparsec-internal)
Completed    attoparsec-0.14.4 (lib:attoparsec-internal)
Starting     time-compat-1.9.6.1 (lib)
Building     time-compat-1.9.6.1 (lib)
Installing   async-2.2.4 (lib)
Installing   base-compat-0.12.2 (lib)
Completed    async-2.2.4 (lib)
Starting     unliftio-0.2.22.0 (lib)
Completed    base-compat-0.12.2 (lib)
Starting     base-compat-batteries-0.12.2 (lib)
Building     unliftio-0.2.22.0 (lib)
Building     base-compat-batteries-0.12.2 (lib)
Installing   time-compat-1.9.6.1 (lib)
Completed    time-compat-1.9.6.1 (lib)
Installing   primitive-0.7.4.0 (lib)
Completed    primitive-0.7.4.0 (lib)
Starting     scientific-0.3.7.0 (lib)
Building     scientific-0.3.7.0 (lib)
Installing   unliftio-0.2.22.0 (lib)
Completed    unliftio-0.2.22.0 (lib)
Installing   scientific-0.3.7.0 (lib)
Completed    scientific-0.3.7.0 (lib)
Starting     attoparsec-0.14.4 (lib)
Building     attoparsec-0.14.4 (lib)
Installing   base-compat-batteries-0.12.2 (lib)
Completed    base-compat-batteries-0.12.2 (lib)
Installing   attoparsec-0.14.4 (lib)
Completed    attoparsec-0.14.4 (lib)
Starting     attoparsec-iso8601-1.0.2.1 (lib)
Building     attoparsec-iso8601-1.0.2.1 (lib)
Installing   attoparsec-iso8601-1.0.2.1 (lib)
Completed    attoparsec-iso8601-1.0.2.1 (lib)
Configuring library for hermes-json-0.2.0.0..
Preprocessing library for hermes-json-0.2.0.0..
Building library for hermes-json-0.2.0.0..
[ 1 of 10] Compiling Data.Hermes.SIMDJSON.Types ( src/Data/Hermes/SIMDJSON/Types.hs, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes/SIMDJSON/Types.o, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes/SIMDJSON/Types.dyn_o )
[ 2 of 10] Compiling Data.Hermes.SIMDJSON.Bindings ( src/Data/Hermes/SIMDJSON/Bindings.hs, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes/SIMDJSON/Bindings.o, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes/SIMDJSON/Bindings.dyn_o )
[ 3 of 10] Compiling Data.Hermes.SIMDJSON.Wrapper ( src/Data/Hermes/SIMDJSON/Wrapper.hs, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes/SIMDJSON/Wrapper.o, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes/SIMDJSON/Wrapper.dyn_o )
[ 4 of 10] Compiling Data.Hermes.SIMDJSON ( src/Data/Hermes/SIMDJSON.hs, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes/SIMDJSON.o, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes/SIMDJSON.dyn_o )
[ 5 of 10] Compiling Data.Hermes.Decoder.Types ( src/Data/Hermes/Decoder/Types.hs, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes/Decoder/Types.o, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes/Decoder/Types.dyn_o )
[ 6 of 10] Compiling Data.Hermes.Decoder.Path ( src/Data/Hermes/Decoder/Path.hs, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes/Decoder/Path.o, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes/Decoder/Path.dyn_o )
[ 7 of 10] Compiling Data.Hermes.Decoder.Value ( src/Data/Hermes/Decoder/Value.hs, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes/Decoder/Value.o, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes/Decoder/Value.dyn_o )
[ 8 of 10] Compiling Data.Hermes.Decoder.Time ( src/Data/Hermes/Decoder/Time.hs, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes/Decoder/Time.o, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes/Decoder/Time.dyn_o )
[ 9 of 10] Compiling Data.Hermes.Decoder ( src/Data/Hermes/Decoder.hs, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes/Decoder.o, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes/Decoder.dyn_o )
[10 of 10] Compiling Data.Hermes      ( src/Data/Hermes.hs, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes.o, /Users/gregory/Haskell/hermes/dist-newstyle/build/x86_64-osx/ghc-9.4.1/hermes-json-0.2.0.0/build/Data/Hermes.dyn_o )
ld: warning: -undefined dynamic_lookup may not work with chained fixups

**Comment by velveteer** [comment]
I've released https://hackage.haskell.org/package/hermes-json-0.2.0.1, which includes support for GHC 9.4.1. Thanks for reporting this!

**Comment by funarog** [comment]
Wonderful!Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Josh Miller ***@***.***> Date: 10/10/22  2:05 PM  (GMT-06:00) To: velveteer/hermes ***@***.***> Cc: Greg ***@***.***>, Author ***@***.***> Subject: Re: [velveteer/hermes] Where are the build instructions? (Issue #15) 
I've released https://hackage.haskell.org/package/hermes-json-0.2.0.1, which includes support for GHC 9.4.1. Thanks for reporting this!
