### ISSUE TITLE
Null byte emits arbitrary garbage data

### ISSUE THREAD

**Issue by ysangkok** [velveteer/hermes#2]
```
repl> newtype Person = Person Int deriving Show
repl> personDecoder = withObject $ \obj -> Person <$> atKey "lol" int obj
repl> decodeEither personDecoder "\x00"
Left (SIMDException (HError {path = "", errorMsg = "A JSON document made of a scalar (number, Boolean, null or string) is treated as a value. Use get_bool(), get_double(), etc. on the document instead. ", docLocation = "", docDebug = "json_iterator [ depth : 1, structural : '\NUL/\DEL\NUL\NULO\aB\NUL\NUL\NULA\nB\NUL\NUL\NULh(\DEL\NUL\NUL\SOH\NUL\NUL\NUL"}))
repl> decodeEither personDecoder "\x00"
Left (SIMDException (HError {path = "", errorMsg = "A JSON document made of a scalar (number, Boolean, null or string) is treated as a value. Use get_bool(), get_double(), etc. on the document instead. ", docLocation = "", docDebug = "json_iterator [ depth : 1, structural : '\NULM\ETXB\NUL\NUL\NUL`(\DEL\NUL\NUL9M\ETXB\NUL\NUL\NUL7M\ETXB\NUL\NUL\NUL\EMe^\EOT"}))
repl> decodeEither personDecoder "\x00"
Left (SIMDException (HError {path = "", errorMsg = "A JSON document made of a scalar (number, Boolean, null or string) is treated as a value. Use get_bool(), get_double(), etc. on the document instead. ", docLocation = "", docDebug = "json_iterator [ depth : 1, structural : '\NUL\STX\tB\NUL\NUL\NULy\ETXB\NUL\NUL\NULJ~\ETXB\NUL\NUL\NULh(\DEL\NUL\NUL\SOH\NUL\NUL\NUL"}))
```

Scroll to the end of the line to see some garbage data.

The fact that the same input bytestring returns unequal errors breaks referential transparency, which users expect.

This also makes it harder to use Hermes in property testing.

Here is an expression that I would expect to be `True`:

    repl> fromLeft undefined (decodeEither personDecoder "\x00") == fromLeft undefined (decodeEither personDecoder "\x00")
    False

**Comment by velveteer** [comment]
Thanks for another great find! This makes sense, the library doesn't support scalar documents, but simdjson is still trying to read the structural index from the iterator...which becomes null and then I guess my `strcpy` copies garbage. It seems the best solution here is to not generate the debug string when the `SCALAR_DOCUMENT_AS_VALUE` error is thrown. I am hoping 92d87284bfa04fae660a91c4d865bcc47c9303d8 covers this.

**Comment by ysangkok** [comment]
Indeed, it was fixed by that commit, thanks a lot for the quick response.
