### ISSUE TITLE
Benchmarks should specify version of compiler/Aeson used and its flags

### ISSUE THREAD

**Issue by ysangkok** [velveteer/hermes#9]
I just found out about the `cffi` flag for Aeson. It would be nice to know whether the benchmarks in the readme were performed with or without that flag set.

**Comment by velveteer** [comment]
Looks like the cffi flag is going away: https://www.github.com/haskell/aeson/issues/992

The benchmarks specify that we're using text >= 2.0, which is best for both us and aeson.
